### ISSUE TITLE
Failed compile on Lion

### ISSUE THREAD

**Issue by phaseOne** [tj/node-discount#17]
I have node v0.6.14 installed, but when I attempt to install the package with `npm install`, it fails. Even when I `sudo !!`.

I am assuming I need to install a missing dev tool, but I cannot pinpoint what I need to install.

This is the output:

```
npm http GET https://registry.npmjs.org/discount
npm http 304 https://registry.npmjs.org/discount

> discount@0.2.3 preinstall /Users/evan/node/SodiumWiki/node_modules/discount
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for pkg-config version >= 0.0.0 : pkg-config was not found 
/Users/evan/node/SodiumWiki/node_modules/discount/wscript:11: error: the configuration failed (see '/Users/evan/node/SodiumWiki/node_modules/discount/build/config.log')

npm ERR! discount@0.2.3 preinstall: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the discount@0.2.3 preinstall script.
npm ERR! This is most likely a problem with the discount package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls discount
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/evan/node/SodiumWiki
npm ERR! node -v v0.6.14
npm ERR! npm -v 1.1.12
npm ERR! code ELIFECYCLE
npm ERR! message discount@0.2.3 preinstall: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/evan/node/SodiumWiki/npm-debug.log
npm not ok
```

**Comment by phaseOne** [comment]
I think this is the point of failure (found in npm-debug.log):

```
verbose loadDefaults discount@0.2.3
info preinstall discount@0.2.3
verbose unsafe-perm in lifecycle false
verbose Setting uid from 0 501
verbose stack at uid setting Error
verbose stack at uid setting     at exec (/usr/local/lib/node_modules/npm/lib/utils/exec.js:35:17)
verbose stack at uid setting     at Array.0 (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:146:5)
verbose stack at uid setting     at EventEmitter._tickCallback (node.js:192:40)
silly exec sh "-c" "node-waf configure build"
silly spawning [ 'sh',
silly spawning   [ '-c', 'node-waf configure build' ],
silly spawning   '/Users/evan/node/SodiumWiki/node_modules/discount' ]
info discount@0.2.3 Failed to exec preinstall script
```

**Comment by phaseOne** [comment]
No change with node v0.6.15

**Comment by phaseOne** [comment]
Wow. I am insane.

```
brew install pkg-config
```

Problem solved.

And if you don't have homebrew:

```
/usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
```

Then run:

```
brew install pkg-config
```
