### ISSUE TITLE
doesn't compile on Solaris

### ISSUE THREAD

**Issue by isaacs** [tj/node-discount#7]
Here's the output:

```
[node@b274384b-e59b-4733-ac19-3a7e0c8a0f52 ~/node_modules]$ npm install discount

> discount@0.1.2 preinstall /home/node/node_modules/discount
> node-waf configure build

Checking for program g++ or c++          : /home/node/local/bin/g++ 
Checking for program cpp                 : /home/node/local/bin/cpp 
Checking for program ar                  : /opt/local/bin/ar 
Checking for program ranlib              : /opt/local/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /home/node/.node_libraries:/opt/nodejs/node_modules:/home/node/local/lib/node 
Checking for node prefix                 : ok /opt/nodejs/v0.4.5 
Checking for library markdown            : yes 
'configure' finished successfully (0.278s)
Waf: Entering directory `/home/node/node_modules/discount/build'
[1/2] cxx: src/markdown.cc -> build/default/src/markdown_1.o
../src/markdown.cc:12:21: mkdio.h: No such file or directory
../src/markdown.cc: In function `v8::Handle<v8::Value> Parse(const v8::Arguments&)':
../src/markdown.cc:29: error: `MMIOT' was not declared in this scope
../src/markdown.cc:29: error: `doc' was not declared in this scope
../src/markdown.cc:31: error: `mkd_string' was not declared in this scope
../src/markdown.cc:33: error: `mkd_compile' was not declared in this scope
../src/markdown.cc:34: error: `mkd_document' was not declared in this scope
../src/markdown.cc:36: error: `mkd_cleanup' was not declared in this scope
../src/markdown.cc:50:2: warning: no newline at end of file
Waf: Leaving directory `/home/node/node_modules/discount/build'
Build failed:  -> task failed (err #1): 
        {task: cxx markdown.cc -> markdown_1.o}
npm ERR! error installing discount@0.1.2 Error: discount@0.1.2 preinstall: `node-waf configure build`
npm ERR! error installing discount@0.1.2 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing discount@0.1.2     at ChildProcess.<anonymous> (/home/node/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing discount@0.1.2     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing discount@0.1.2     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! discount@0.1.2 preinstall: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the discount@0.1.2 preinstall script.
npm ERR! This is most likely a problem with the discount package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls discount
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System SunOS 5.11
npm ERR! command "node" "/home/node/local/bin/npm" "install" "discount"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/node/node_modules/npm-debug.log
npm not ok

[node@b274384b-e59b-4733-ac19-3a7e0c8a0f52 ~/node_modules]$ find /opt/local -name mkdio.h
/opt/local/include/mkdio.h

[node@b274384b-e59b-4733-ac19-3a7e0c8a0f52 ~/node_modules]$ find /opt/local -name libmarkdown.*
/opt/local/lib/libmarkdown.a
```

Note that I've already installed markdown with pkgin, so there's a mkdio.h and libmarkdown present.

**Comment by tj** [comment]
hmmmm I have:

```
libpath = ['/usr/lib', '/usr/local/lib', '/opt/local/lib'],
```

maybe we just need /opt/local in there

**Comment by tj** [comment]
haha... nvm... it's there

**Comment by slaskis** [comment]
Adding the include path worked for me (on no.de): https://github.com/slaskis/node-discount/commit/46c2c60a6e6b22b0325ba6a21d685dd4acb9efc5

I can't find the github 'pull request'-button otherwise i'd make one of those for you

**Comment by c4milo** [comment]
I'm having this issue in OSX Lion as well.

**Comment by smebberson** [comment]
I'm also having this issue on OSX lion

**Comment by visnup** [comment]
`Orc/discount` at `b9c8403` for whatever reason wasn't finding `strcasecmp` w/o a `strings.h`. latest seems to configure correctly on osx 10.8 (and presumably on 10.7.x and solaris), generating a `mkdio.h` that gets picked up correctly again.
